name: Podman Test CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
concurrency:
  group: podman-test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: 'windows-2025'
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup Podman CLI For Windows
        run: |
          winget install --id jazzdelightsme.WingetPathUpdater --source winget
          winget install RedHat.Podman --source winget
          podman machine init
          podman machine set --rootful
          podman machine start
          $podmanPipeLocation = podman machine inspect --format '{{.ConnectionInfo.PodmanPipe.Path}}'
          "DOCKER_HOST=npipe://$podmanPipeLocation" >> $env:GITHUB_ENV
          "PATH=$env:PATH" >> $env:GITHUB_ENV
      - name: Test Docker CLI on Windows Server
        run: |
          docker context ls
          podman run docker.io/library/hello-world:linux
          docker run hello-world:linux
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'maven'
      - name: Run test with JDK
        run: ./mvnw clean test
