name: Second Test CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
concurrency:
  group: second-test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: 'windows-2025'
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup WSL 2 and Ubuntu Linux distribution
        uses: Vampire/setup-wsl@v5
        with:
          distribution: 'Ubuntu-24.04'
          use-cache: 'true'
      - name: Setup Rancher Desktop on Windows Server without GUI
        run: |
          choco install rancher-desktop
          Import-Module "$env:ChocolateyInstall/helpers/chocolateyInstaller.psm1"
          refreshenv
          rdctl set --container-engine.name=moby --kubernetes.enabled=false
          rdctl start --application.start-in-background
          docker run hello-world:linux
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'maven'
      - name: Run test with JDK
        run: ./mvnw clean test
