name: Second Test CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
concurrency:
  group: second-test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: 'windows-latest'
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup WSL 2 and Ubuntu Linux distribution
        uses: Vampire/setup-wsl@v5
        with:
          distribution: 'Ubuntu-24.04'
          use-cache: 'true'
      - name: Setup Docker daemon on Linux distribution on WSL without GUI
        shell: wsl-bash {0}
        run: |
          sudo apt-get update
          sudo apt-get remove docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc
          sudo apt-get install ca-certificates curl -y
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
          curl -fsSL https://raw.githubusercontent.com/lbruun-net/docker-free/main/docker-create-certs.sh | bash
          sudo mkdir -p /etc/systemd/system/docker.service.d
          sudo cat <<EOF > /etc/systemd/system/docker.service.d/override.conf
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock \
            -H=tcp://0.0.0.0:12376 \
            --tlsverify=true \
            --tlscacert=/etc/docker/certs/ca.pem \
            --tlscert=/etc/docker/certs/cert.pem \
            --tlskey=/etc/docker/certs/key.pem
          EOF
          sudo systemctl daemon-reload
          sudo systemctl restart docker.service
      - name: Test Docker CLI on Windows Server without GUI
        env:
          DOCKER_HOST: 'tcp://localhost:12376'
          DOCKER_TLS_VERIFY: '1'
          DOCKER_CERT_PATH: '\\wsl$\Ubuntu-24.04\root\.docker'
        run: docker run hello-world:linux
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
          cache: 'maven'
      - name: Run test with JDK
        env:
          DOCKER_HOST: 'tcp://localhost:12376'
          DOCKER_TLS_VERIFY: '1'
          DOCKER_CERT_PATH: '\\wsl$\Ubuntu-24.04\root\.docker'
        run: ./mvnw clean test
